// entity_signals.h


// For each signal needed at the level of class entity, add a line of the form:
//   MAC( SIGNAL, "owner::SIGNAL" )

// @Patch - replaced with spidey ones
MAC( ACTIVATED_BY_CHARACTER, "entity::ACTIVATED_BY_CHARACTER" )

MAC( DAMAGED, "entity::DAMAGED" )
MAC( DESTROYED, "entity::DESTROYED" )
MAC( RADIO_DETONATE, "entity::RADIO_DETONATE" )
MAC( USE_ITEM, "entity::USE_ITEM" )
MAC( ANIM_ACTION, "entity::ANIM_ACTION" )
MAC( ATTACK_BEGIN, "entity::ATTACK_BEGIN" )
MAC( ATTACK_END, "entity::ATTACK_END" )
MAC( ATTACK, "entity::ATTACK" )
MAC( FOOTSTEP_L, "entity::FOOTSTEP_L" )
MAC( FOOTSTEP_R, "entity::FOOTSTEP_R" )
MAC( RUMBLE_LOW, "entity::RUMBLE_LOW" )
MAC( RUMBLE_MEDIUM, "entity::RUMBLE_MEDIUM" )
MAC( RUMBLE_HIGH, "entity::RUMBLE_HIGH" )
MAC( RUMBLE_STOP, "entity::RUMBLE_STOP" )
MAC( AI_STATE_IDLE, "entity::AI_STATE_IDLE" )
MAC( AI_STATE_ALERTED, "entity::AI_STATE_ALERTED" )
MAC( AI_STATE_COMBAT, "entity::AI_STATE_COMBAT" )
MAC( AI_STATE_INCREMENT, "entity::AI_STATE_INCREMENT" )
MAC( AI_STATE_DECREMENT, "entity::AI_STATE_DECREMENT" )
MAC( AI_BOSS_SIGNAL_1, "entity::AI_BOSS_SIGNAL_1" )
MAC( AI_BOSS_SIGNAL_2, "entity::AI_BOSS_SIGNAL_2" )
MAC( AI_BOSS_SIGNAL_3, "entity::AI_BOSS_SIGNAL_3" )
MAC( AI_BOSS_SIGNAL_4, "entity::AI_BOSS_SIGNAL_4" )
MAC( GENERIC_SIGNAL_1, "entity::GENERIC_SIGNAL_1" )
MAC( GENERIC_SIGNAL_2, "entity::GENERIC_SIGNAL_2" )
MAC( GENERIC_SIGNAL_3, "entity::GENERIC_SIGNAL_3" )

MAC( GENERIC_SIGNAL_4, "entity::GENERIC_SIGNAL_4" )
MAC( GENERIC_SIGNAL_5, "entity::GENERIC_SIGNAL_5" )
MAC( FADED_OUT, "entity::FADED_OUT" )
MAC( SCENE_ANIM_FINISHED, "entity::SCENE_ANIM_FINISHED" )
MAC( SCENE_ANIM_ENDING, "entity::SCENE_ANIM_ENDING" )
MAC( BOUNCED, "entity::BOUNCED" )
MAC( AI_NEW_THREAT, "entity::AI_NEW_THREAT" )
MAC( AI_LOST_THREAT, "entity::AI_LOST_THREAT" )

MAC( PICKED_UP, "entity::PICKED_UP" )
MAC( PUT_DOWN, "entity::PUT_DOWN" )
MAC( BEING_WEBBED, "entity::BEING_WEBBED" )
